version: '3.9'

services:
  db:
    image: postgres:16
    container_name: car_auction_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_auction_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carauction
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d car_auction_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: car_auction_pgadmin
  #  restart: unless-stopped
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  ports:
  #    - "5050:80"
  #  depends_on:
  #    - db
  #  networks:
  #    - carauction

  webapi:
    build:
      context: .
      dockerfile: src/CarAuctionManagementSystem.Api/Dockerfile
    ports:
      - "8090:8090"
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - carauction

volumes:
  pgdata:

networks:
  carauction: